package biosig;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class biosigJNI {
  public final static native void imaxdiv_t_quot_set(long jarg1, imaxdiv_t jarg1_, long jarg2);
  public final static native long imaxdiv_t_quot_get(long jarg1, imaxdiv_t jarg1_);
  public final static native void imaxdiv_t_rem_set(long jarg1, imaxdiv_t jarg1_, long jarg2);
  public final static native long imaxdiv_t_rem_get(long jarg1, imaxdiv_t jarg1_);
  public final static native long new_imaxdiv_t();
  public final static native void delete_imaxdiv_t(long jarg1);
  public final static native long imaxabs(long jarg1);
  public final static native long imaxdiv(long jarg1, long jarg2);
  public final static native long strtoimax(String jarg1, long jarg2, int jarg3);
  public final static native java.math.BigInteger strtoumax(String jarg1, long jarg2, int jarg3);
  public final static native void CHANNEL_TYPE_PhysMin_set(long jarg1, CHANNEL_TYPE jarg1_, double jarg2);
  public final static native double CHANNEL_TYPE_PhysMin_get(long jarg1, CHANNEL_TYPE jarg1_);
  public final static native void CHANNEL_TYPE_PhysMax_set(long jarg1, CHANNEL_TYPE jarg1_, double jarg2);
  public final static native double CHANNEL_TYPE_PhysMax_get(long jarg1, CHANNEL_TYPE jarg1_);
  public final static native void CHANNEL_TYPE_DigMin_set(long jarg1, CHANNEL_TYPE jarg1_, double jarg2);
  public final static native double CHANNEL_TYPE_DigMin_get(long jarg1, CHANNEL_TYPE jarg1_);
  public final static native void CHANNEL_TYPE_DigMax_set(long jarg1, CHANNEL_TYPE jarg1_, double jarg2);
  public final static native double CHANNEL_TYPE_DigMax_get(long jarg1, CHANNEL_TYPE jarg1_);
  public final static native void CHANNEL_TYPE_Cal_set(long jarg1, CHANNEL_TYPE jarg1_, double jarg2);
  public final static native double CHANNEL_TYPE_Cal_get(long jarg1, CHANNEL_TYPE jarg1_);
  public final static native void CHANNEL_TYPE_Off_set(long jarg1, CHANNEL_TYPE jarg1_, double jarg2);
  public final static native double CHANNEL_TYPE_Off_get(long jarg1, CHANNEL_TYPE jarg1_);
  public final static native void CHANNEL_TYPE_OnOff_set(long jarg1, CHANNEL_TYPE jarg1_, char jarg2);
  public final static native char CHANNEL_TYPE_OnOff_get(long jarg1, CHANNEL_TYPE jarg1_);
  public final static native void CHANNEL_TYPE_Label_set(long jarg1, CHANNEL_TYPE jarg1_, String jarg2);
  public final static native String CHANNEL_TYPE_Label_get(long jarg1, CHANNEL_TYPE jarg1_);
  public final static native void CHANNEL_TYPE_LeadIdCode_set(long jarg1, CHANNEL_TYPE jarg1_, int jarg2);
  public final static native int CHANNEL_TYPE_LeadIdCode_get(long jarg1, CHANNEL_TYPE jarg1_);
  public final static native void CHANNEL_TYPE_Transducer_set(long jarg1, CHANNEL_TYPE jarg1_, String jarg2);
  public final static native String CHANNEL_TYPE_Transducer_get(long jarg1, CHANNEL_TYPE jarg1_);
  public final static native void CHANNEL_TYPE_PhysDimCode_set(long jarg1, CHANNEL_TYPE jarg1_, int jarg2);
  public final static native int CHANNEL_TYPE_PhysDimCode_get(long jarg1, CHANNEL_TYPE jarg1_);
  public final static native void CHANNEL_TYPE_TOffset_set(long jarg1, CHANNEL_TYPE jarg1_, float jarg2);
  public final static native float CHANNEL_TYPE_TOffset_get(long jarg1, CHANNEL_TYPE jarg1_);
  public final static native void CHANNEL_TYPE_LowPass_set(long jarg1, CHANNEL_TYPE jarg1_, float jarg2);
  public final static native float CHANNEL_TYPE_LowPass_get(long jarg1, CHANNEL_TYPE jarg1_);
  public final static native void CHANNEL_TYPE_HighPass_set(long jarg1, CHANNEL_TYPE jarg1_, float jarg2);
  public final static native float CHANNEL_TYPE_HighPass_get(long jarg1, CHANNEL_TYPE jarg1_);
  public final static native void CHANNEL_TYPE_Notch_set(long jarg1, CHANNEL_TYPE jarg1_, float jarg2);
  public final static native float CHANNEL_TYPE_Notch_get(long jarg1, CHANNEL_TYPE jarg1_);
  public final static native void CHANNEL_TYPE_XYZ_set(long jarg1, CHANNEL_TYPE jarg1_, long jarg2);
  public final static native long CHANNEL_TYPE_XYZ_get(long jarg1, CHANNEL_TYPE jarg1_);
  public final static native void CHANNEL_TYPE_Impedance_set(long jarg1, CHANNEL_TYPE jarg1_, float jarg2);
  public final static native float CHANNEL_TYPE_Impedance_get(long jarg1, CHANNEL_TYPE jarg1_);
  public final static native void CHANNEL_TYPE_fZ_set(long jarg1, CHANNEL_TYPE jarg1_, float jarg2);
  public final static native float CHANNEL_TYPE_fZ_get(long jarg1, CHANNEL_TYPE jarg1_);
  public final static native void CHANNEL_TYPE_GDFTYP_set(long jarg1, CHANNEL_TYPE jarg1_, int jarg2);
  public final static native int CHANNEL_TYPE_GDFTYP_get(long jarg1, CHANNEL_TYPE jarg1_);
  public final static native void CHANNEL_TYPE_SPR_set(long jarg1, CHANNEL_TYPE jarg1_, long jarg2);
  public final static native long CHANNEL_TYPE_SPR_get(long jarg1, CHANNEL_TYPE jarg1_);
  public final static native long new_CHANNEL_TYPE();
  public final static native void delete_CHANNEL_TYPE(long jarg1);
  public final static native void HDRTYPE_VERSION_set(long jarg1, HDRTYPE jarg1_, float jarg2);
  public final static native float HDRTYPE_VERSION_get(long jarg1, HDRTYPE jarg1_);
  public final static native void HDRTYPE_FileName_set(long jarg1, HDRTYPE jarg1_, String jarg2);
  public final static native String HDRTYPE_FileName_get(long jarg1, HDRTYPE jarg1_);
  public final static native void HDRTYPE_TYPE_set(long jarg1, HDRTYPE jarg1_, int jarg2);
  public final static native int HDRTYPE_TYPE_get(long jarg1, HDRTYPE jarg1_);
  public final static native void HDRTYPE_IPaddr_set(long jarg1, HDRTYPE jarg1_, long jarg2);
  public final static native long HDRTYPE_IPaddr_get(long jarg1, HDRTYPE jarg1_);
  public final static native void HDRTYPE_SampleRate_set(long jarg1, HDRTYPE jarg1_, double jarg2);
  public final static native double HDRTYPE_SampleRate_get(long jarg1, HDRTYPE jarg1_);
  public final static native void HDRTYPE_NRec_set(long jarg1, HDRTYPE jarg1_, long jarg2);
  public final static native long HDRTYPE_NRec_get(long jarg1, HDRTYPE jarg1_);
  public final static native void HDRTYPE_T0_set(long jarg1, HDRTYPE jarg1_, long jarg2);
  public final static native long HDRTYPE_T0_get(long jarg1, HDRTYPE jarg1_);
  public final static native void HDRTYPE_HeadLen_set(long jarg1, HDRTYPE jarg1_, long jarg2);
  public final static native long HDRTYPE_HeadLen_get(long jarg1, HDRTYPE jarg1_);
  public final static native void HDRTYPE_SPR_set(long jarg1, HDRTYPE jarg1_, long jarg2);
  public final static native long HDRTYPE_SPR_get(long jarg1, HDRTYPE jarg1_);
  public final static native void HDRTYPE_LOC_set(long jarg1, HDRTYPE jarg1_, long jarg2);
  public final static native long HDRTYPE_LOC_get(long jarg1, HDRTYPE jarg1_);
  public final static native void HDRTYPE_NS_set(long jarg1, HDRTYPE jarg1_, int jarg2);
  public final static native int HDRTYPE_NS_get(long jarg1, HDRTYPE jarg1_);
  public final static native void HDRTYPE_tzmin_set(long jarg1, HDRTYPE jarg1_, short jarg2);
  public final static native short HDRTYPE_tzmin_get(long jarg1, HDRTYPE jarg1_);
  public final static native void HDRTYPE_rerefCHANNEL_set(long jarg1, HDRTYPE jarg1_, long jarg2, CHANNEL_TYPE jarg2_);
  public final static native long HDRTYPE_rerefCHANNEL_get(long jarg1, HDRTYPE jarg1_);
  public final static native void HDRTYPE_CHANNEL_set(long jarg1, HDRTYPE jarg1_, long jarg2, CHANNEL_TYPE jarg2_);
  public final static native long HDRTYPE_CHANNEL_get(long jarg1, HDRTYPE jarg1_);
  public final static native long HDRTYPE_aECG_get(long jarg1, HDRTYPE jarg1_);
  public final static native long new_HDRTYPE();
  public final static native void delete_HDRTYPE(long jarg1);
  public final static native long constructHDR(long jarg1, long jarg2);
  public final static native void destructHDR(long jarg1, HDRTYPE jarg1_);
  public final static native long sopen(String jarg1, String jarg2, long jarg3, HDRTYPE jarg3_);
  public final static native int sclose(long jarg1, HDRTYPE jarg1_);
  public final static native long sread(long jarg1, long jarg2, long jarg3, long jarg4, HDRTYPE jarg4_);
  public final static native long swrite(long jarg1, long jarg2, long jarg3, HDRTYPE jarg3_);
  public final static native int seof(long jarg1, HDRTYPE jarg1_);
  public final static native void srewind(long jarg1, HDRTYPE jarg1_);
  public final static native int sseek(long jarg1, HDRTYPE jarg1_, int jarg2, int jarg3);
  public final static native int stell(long jarg1, HDRTYPE jarg1_);
  public final static native int serror2(long jarg1, HDRTYPE jarg1_);
  public final static native int hdr2ascii__SWIG_0(long jarg1, HDRTYPE jarg1_, long jarg2, int jarg3);
  public final static native int RerefCHANNEL(long jarg1, HDRTYPE jarg1_, long jarg2, char jarg3);
  public final static native String GetFileTypeString(int jarg1);
  public final static native int PhysDimCode(String jarg1);
  public final static native String PhysDim3(int jarg1);
  public final static native void serror();
  public final static native void hdr2ascii__SWIG_1(long jarg1, HDRTYPE jarg1_, int jarg2);
}
