package biosig;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class CHANNEL_TYPE {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CHANNEL_TYPE(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CHANNEL_TYPE obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        biosigJNI.delete_CHANNEL_TYPE(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPhysMin(double value) {
    biosigJNI.CHANNEL_TYPE_PhysMin_set(swigCPtr, this, value);
  }

  public double getPhysMin() {
    return biosigJNI.CHANNEL_TYPE_PhysMin_get(swigCPtr, this);
  }

  public void setPhysMax(double value) {
    biosigJNI.CHANNEL_TYPE_PhysMax_set(swigCPtr, this, value);
  }

  public double getPhysMax() {
    return biosigJNI.CHANNEL_TYPE_PhysMax_get(swigCPtr, this);
  }

  public void setDigMin(double value) {
    biosigJNI.CHANNEL_TYPE_DigMin_set(swigCPtr, this, value);
  }

  public double getDigMin() {
    return biosigJNI.CHANNEL_TYPE_DigMin_get(swigCPtr, this);
  }

  public void setDigMax(double value) {
    biosigJNI.CHANNEL_TYPE_DigMax_set(swigCPtr, this, value);
  }

  public double getDigMax() {
    return biosigJNI.CHANNEL_TYPE_DigMax_get(swigCPtr, this);
  }

  public void setCal(double value) {
    biosigJNI.CHANNEL_TYPE_Cal_set(swigCPtr, this, value);
  }

  public double getCal() {
    return biosigJNI.CHANNEL_TYPE_Cal_get(swigCPtr, this);
  }

  public void setOff(double value) {
    biosigJNI.CHANNEL_TYPE_Off_set(swigCPtr, this, value);
  }

  public double getOff() {
    return biosigJNI.CHANNEL_TYPE_Off_get(swigCPtr, this);
  }

  public void setOnOff(char value) {
    biosigJNI.CHANNEL_TYPE_OnOff_set(swigCPtr, this, value);
  }

  public char getOnOff() {
    return biosigJNI.CHANNEL_TYPE_OnOff_get(swigCPtr, this);
  }

  public void setLabel(String value) {
    biosigJNI.CHANNEL_TYPE_Label_set(swigCPtr, this, value);
  }

  public String getLabel() {
    return biosigJNI.CHANNEL_TYPE_Label_get(swigCPtr, this);
  }

  public void setLeadIdCode(int value) {
    biosigJNI.CHANNEL_TYPE_LeadIdCode_set(swigCPtr, this, value);
  }

  public int getLeadIdCode() {
    return biosigJNI.CHANNEL_TYPE_LeadIdCode_get(swigCPtr, this);
  }

  public void setTransducer(String value) {
    biosigJNI.CHANNEL_TYPE_Transducer_set(swigCPtr, this, value);
  }

  public String getTransducer() {
    return biosigJNI.CHANNEL_TYPE_Transducer_get(swigCPtr, this);
  }

  public void setPhysDimCode(int value) {
    biosigJNI.CHANNEL_TYPE_PhysDimCode_set(swigCPtr, this, value);
  }

  public int getPhysDimCode() {
    return biosigJNI.CHANNEL_TYPE_PhysDimCode_get(swigCPtr, this);
  }

  public void setTOffset(float value) {
    biosigJNI.CHANNEL_TYPE_TOffset_set(swigCPtr, this, value);
  }

  public float getTOffset() {
    return biosigJNI.CHANNEL_TYPE_TOffset_get(swigCPtr, this);
  }

  public void setLowPass(float value) {
    biosigJNI.CHANNEL_TYPE_LowPass_set(swigCPtr, this, value);
  }

  public float getLowPass() {
    return biosigJNI.CHANNEL_TYPE_LowPass_get(swigCPtr, this);
  }

  public void setHighPass(float value) {
    biosigJNI.CHANNEL_TYPE_HighPass_set(swigCPtr, this, value);
  }

  public float getHighPass() {
    return biosigJNI.CHANNEL_TYPE_HighPass_get(swigCPtr, this);
  }

  public void setNotch(float value) {
    biosigJNI.CHANNEL_TYPE_Notch_set(swigCPtr, this, value);
  }

  public float getNotch() {
    return biosigJNI.CHANNEL_TYPE_Notch_get(swigCPtr, this);
  }

  public void setXYZ(SWIGTYPE_p_float value) {
    biosigJNI.CHANNEL_TYPE_XYZ_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getXYZ() {
    long cPtr = biosigJNI.CHANNEL_TYPE_XYZ_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setImpedance(float value) {
    biosigJNI.CHANNEL_TYPE_Impedance_set(swigCPtr, this, value);
  }

  public float getImpedance() {
    return biosigJNI.CHANNEL_TYPE_Impedance_get(swigCPtr, this);
  }

  public void setFZ(float value) {
    biosigJNI.CHANNEL_TYPE_fZ_set(swigCPtr, this, value);
  }

  public float getFZ() {
    return biosigJNI.CHANNEL_TYPE_fZ_get(swigCPtr, this);
  }

  public void setGDFTYP(int value) {
    biosigJNI.CHANNEL_TYPE_GDFTYP_set(swigCPtr, this, value);
  }

  public int getGDFTYP() {
    return biosigJNI.CHANNEL_TYPE_GDFTYP_get(swigCPtr, this);
  }

  public void setSPR(long value) {
    biosigJNI.CHANNEL_TYPE_SPR_set(swigCPtr, this, value);
  }

  public long getSPR() {
    return biosigJNI.CHANNEL_TYPE_SPR_get(swigCPtr, this);
  }

  public CHANNEL_TYPE() {
    this(biosigJNI.new_CHANNEL_TYPE(), true);
  }

}
