package biosig;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class FileFormat {
  public final static FileFormat noFile = new FileFormat("noFile");
  public final static FileFormat unknown = new FileFormat("unknown");
  public final static FileFormat ABF = new FileFormat("ABF");
  public final static FileFormat ACQ = new FileFormat("ACQ");
  public final static FileFormat ACR_NEMA = new FileFormat("ACR_NEMA");
  public final static FileFormat AIFC = new FileFormat("AIFC");
  public final static FileFormat AIFF = new FileFormat("AIFF");
  public final static FileFormat AINF = new FileFormat("AINF");
  public final static FileFormat alpha = new FileFormat("alpha");
  public final static FileFormat ARFF = new FileFormat("ARFF");
  public final static FileFormat ASCII_IBI = new FileFormat("ASCII_IBI");
  public final static FileFormat ASCII = new FileFormat("ASCII");
  public final static FileFormat AU = new FileFormat("AU");
  public final static FileFormat ASF = new FileFormat("ASF");
  public final static FileFormat ATES = new FileFormat("ATES");
  public final static FileFormat ATF = new FileFormat("ATF");
  public final static FileFormat AVI = new FileFormat("AVI");
  public final static FileFormat Axona = new FileFormat("Axona");
  public final static FileFormat BCI2000 = new FileFormat("BCI2000");
  public final static FileFormat BDF = new FileFormat("BDF");
  public final static FileFormat BESA = new FileFormat("BESA");
  public final static FileFormat BIN = new FileFormat("BIN");
  public final static FileFormat BKR = new FileFormat("BKR");
  public final static FileFormat BLSC = new FileFormat("BLSC");
  public final static FileFormat BMP = new FileFormat("BMP");
  public final static FileFormat BNI = new FileFormat("BNI");
  public final static FileFormat BSCS = new FileFormat("BSCS");
  public final static FileFormat BrainVision = new FileFormat("BrainVision");
  public final static FileFormat BrainVisionVAmp = new FileFormat("BrainVisionVAmp");
  public final static FileFormat BrainVisionMarker = new FileFormat("BrainVisionMarker");
  public final static FileFormat BZ2 = new FileFormat("BZ2");
  public final static FileFormat CDF = new FileFormat("CDF");
  public final static FileFormat CFS = new FileFormat("CFS");
  public final static FileFormat CFWB = new FileFormat("CFWB");
  public final static FileFormat CNT = new FileFormat("CNT");
  public final static FileFormat CTF = new FileFormat("CTF");
  public final static FileFormat DICOM = new FileFormat("DICOM");
  public final static FileFormat DEMG = new FileFormat("DEMG");
  public final static FileFormat EBS = new FileFormat("EBS");
  public final static FileFormat EDF = new FileFormat("EDF");
  public final static FileFormat EEG1100 = new FileFormat("EEG1100");
  public final static FileFormat EEProbe = new FileFormat("EEProbe");
  public final static FileFormat EEProbe2 = new FileFormat("EEProbe2");
  public final static FileFormat EEProbeAvr = new FileFormat("EEProbeAvr");
  public final static FileFormat EGI = new FileFormat("EGI");
  public final static FileFormat EGIS = new FileFormat("EGIS");
  public final static FileFormat ELF = new FileFormat("ELF");
  public final static FileFormat EMBLA = new FileFormat("EMBLA");
  public final static FileFormat EMSA = new FileFormat("EMSA");
  public final static FileFormat ePrime = new FileFormat("ePrime");
  public final static FileFormat ET_MEG = new FileFormat("ET_MEG");
  public final static FileFormat ETG4000 = new FileFormat("ETG4000");
  public final static FileFormat EVENT = new FileFormat("EVENT");
  public final static FileFormat EXIF = new FileFormat("EXIF");
  public final static FileFormat FAMOS = new FileFormat("FAMOS");
  public final static FileFormat FEF = new FileFormat("FEF");
  public final static FileFormat FITS = new FileFormat("FITS");
  public final static FileFormat FLAC = new FileFormat("FLAC");
  public final static FileFormat GDF = new FileFormat("GDF");
  public final static FileFormat GDF1 = new FileFormat("GDF1");
  public final static FileFormat GIF = new FileFormat("GIF");
  public final static FileFormat GTF = new FileFormat("GTF");
  public final static FileFormat GZIP = new FileFormat("GZIP");
  public final static FileFormat HDF = new FileFormat("HDF");
  public final static FileFormat HL7aECG = new FileFormat("HL7aECG");
  public final static FileFormat HEKA = new FileFormat("HEKA");
  public final static FileFormat ISHNE = new FileFormat("ISHNE");
  public final static FileFormat ITX = new FileFormat("ITX");
  public final static FileFormat JPEG = new FileFormat("JPEG");
  public final static FileFormat JSON = new FileFormat("JSON");
  public final static FileFormat Lexicor = new FileFormat("Lexicor");
  public final static FileFormat Matlab = new FileFormat("Matlab");
  public final static FileFormat MFER = new FileFormat("MFER");
  public final static FileFormat MIDI = new FileFormat("MIDI");
  public final static FileFormat MIT = new FileFormat("MIT");
  public final static FileFormat MM = new FileFormat("MM");
  public final static FileFormat MSI = new FileFormat("MSI");
  public final static FileFormat MSVCLIB = new FileFormat("MSVCLIB");
  public final static FileFormat MS_LNK = new FileFormat("MS_LNK");
  public final static FileFormat _native = new FileFormat("_native");
  public final static FileFormat NeuroLoggerHEX = new FileFormat("NeuroLoggerHEX");
  public final static FileFormat NetCDF = new FileFormat("NetCDF");
  public final static FileFormat NEURON = new FileFormat("NEURON");
  public final static FileFormat NEV = new FileFormat("NEV");
  public final static FileFormat NEX1 = new FileFormat("NEX1");
  public final static FileFormat NIFTI = new FileFormat("NIFTI");
  public final static FileFormat OGG = new FileFormat("OGG");
  public final static FileFormat OpenXDF = new FileFormat("OpenXDF");
  public final static FileFormat PBMA = new FileFormat("PBMA");
  public final static FileFormat PBMN = new FileFormat("PBMN");
  public final static FileFormat PDF = new FileFormat("PDF");
  public final static FileFormat PDP = new FileFormat("PDP");
  public final static FileFormat Persyst = new FileFormat("Persyst");
  public final static FileFormat PGMA = new FileFormat("PGMA");
  public final static FileFormat PGMB = new FileFormat("PGMB");
  public final static FileFormat PLEXON = new FileFormat("PLEXON");
  public final static FileFormat PNG = new FileFormat("PNG");
  public final static FileFormat PNM = new FileFormat("PNM");
  public final static FileFormat POLY5 = new FileFormat("POLY5");
  public final static FileFormat PPMA = new FileFormat("PPMA");
  public final static FileFormat PPMB = new FileFormat("PPMB");
  public final static FileFormat PS = new FileFormat("PS");
  public final static FileFormat RDF = new FileFormat("RDF");
  public final static FileFormat RIFF = new FileFormat("RIFF");
  public final static FileFormat SASXPT = new FileFormat("SASXPT");
  public final static FileFormat SCP_ECG = new FileFormat("SCP_ECG");
  public final static FileFormat SIGIF = new FileFormat("SIGIF");
  public final static FileFormat Sigma = new FileFormat("Sigma");
  public final static FileFormat SMA = new FileFormat("SMA");
  public final static FileFormat SND = new FileFormat("SND");
  public final static FileFormat SQLite = new FileFormat("SQLite");
  public final static FileFormat SPSS = new FileFormat("SPSS");
  public final static FileFormat STATA = new FileFormat("STATA");
  public final static FileFormat SVG = new FileFormat("SVG");
  public final static FileFormat SXI = new FileFormat("SXI");
  public final static FileFormat SYNERGY = new FileFormat("SYNERGY");
  public final static FileFormat TIFF = new FileFormat("TIFF");
  public final static FileFormat TMS32 = new FileFormat("TMS32");
  public final static FileFormat TMSiLOG = new FileFormat("TMSiLOG");
  public final static FileFormat TRC = new FileFormat("TRC");
  public final static FileFormat UNIPRO = new FileFormat("UNIPRO");
  public final static FileFormat VRML = new FileFormat("VRML");
  public final static FileFormat VTK = new FileFormat("VTK");
  public final static FileFormat WAV = new FileFormat("WAV");
  public final static FileFormat WG1 = new FileFormat("WG1");
  public final static FileFormat WinEEG = new FileFormat("WinEEG");
  public final static FileFormat WMF = new FileFormat("WMF");
  public final static FileFormat XML = new FileFormat("XML");
  public final static FileFormat XPM = new FileFormat("XPM");
  public final static FileFormat Z = new FileFormat("Z");
  public final static FileFormat ZIP = new FileFormat("ZIP");
  public final static FileFormat ZIP2 = new FileFormat("ZIP2");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FileFormat swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FileFormat.class + " with value " + swigValue);
  }

  private FileFormat(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FileFormat(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FileFormat(String swigName, FileFormat swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FileFormat[] swigValues = { noFile, unknown, ABF, ACQ, ACR_NEMA, AIFC, AIFF, AINF, alpha, ARFF, ASCII_IBI, ASCII, AU, ASF, ATES, ATF, AVI, Axona, BCI2000, BDF, BESA, BIN, BKR, BLSC, BMP, BNI, BSCS, BrainVision, BrainVisionVAmp, BrainVisionMarker, BZ2, CDF, CFS, CFWB, CNT, CTF, DICOM, DEMG, EBS, EDF, EEG1100, EEProbe, EEProbe2, EEProbeAvr, EGI, EGIS, ELF, EMBLA, EMSA, ePrime, ET_MEG, ETG4000, EVENT, EXIF, FAMOS, FEF, FITS, FLAC, GDF, GDF1, GIF, GTF, GZIP, HDF, HL7aECG, HEKA, ISHNE, ITX, JPEG, JSON, Lexicor, Matlab, MFER, MIDI, MIT, MM, MSI, MSVCLIB, MS_LNK, _native, NeuroLoggerHEX, NetCDF, NEURON, NEV, NEX1, NIFTI, OGG, OpenXDF, PBMA, PBMN, PDF, PDP, Persyst, PGMA, PGMB, PLEXON, PNG, PNM, POLY5, PPMA, PPMB, PS, RDF, RIFF, SASXPT, SCP_ECG, SIGIF, Sigma, SMA, SND, SQLite, SPSS, STATA, SVG, SXI, SYNERGY, TIFF, TMS32, TMSiLOG, TRC, UNIPRO, VRML, VTK, WAV, WG1, WinEEG, WMF, XML, XPM, Z, ZIP, ZIP2 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

